export const STATUS_HTTP_VALIDACAO = 422;
export const STATUS_HTTP_NAO_AUTORIZADO = 401;
export const STATUS_HTTP_BAD_REQUEST = 422;
export const STATUS_HTTP_OK = 200;
export const STATUS_HTTP_ERRO_INTERNO = 500;
